name: Create Issue Branch

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create a new branch for the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          first_label=$(echo "${{ github.event.issue.labels }}" | jq -r '.[] | .name | first')

          if [[ "$first_label" == "feat" ]]; then
            branch_name="feat/issue-${issue_number}"
          else
            branch_name="other/${first_label}/issue-${issue_number}"
          fi

          echo "Creating branch: $branch_name"

          echo "Creating branch: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git $BRANCH_NAME

      - name: Add a comment to the issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Branch [$BRANCH_NAME](https://github.com/${{ github.repository }}/tree/$BRANCH_NAME) created for issue #${ISSUE_NUMBER}.'
